### ISSUE TITLE
Error modifying pre-v0.12.0 Grdifinity bins due to rename of "MagnetRelief" to "MagnetRemoveChannel".

### ISSUE THREAD

**Issue by glenn20** [Stu142/FreeCAD-Gridfinity-Workbench#141]
When using Gridfinity Workbench v0.12.0 to modify bins generated with an earlier (pre-v0.12.0) version (eg. change "Height Units"), the following error is generated by FreeCAD and the modified bin fails to be rebuilt:

```
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'MagnetRemoveChannel'
11:39:42  SimpleStorageBin005: 'FeaturePython' object has no attribute 'MagnetRemoveChannel'
```

This seems to have been caused by commit [055ac67](https://github.com/Stu142/FreeCAD-Gridfinity-Workbench/pull/116/changes/055ac6757bd0ec425c31c6ae43cab5a4b210631a) from PR #116.

A simple fix would be to consider reverting that commit to retain backward compatibility or that the break in compatibility be clearly documented for version 0.12.0 advising that gridfinity bins in pre-existing freecad files will have to be deleted and recreated.
