### PR TITLE
Update object properties when modifying bins created with an older version of the Gridfinity Workbench.

### LINKED ISSUE #141: Error modifying pre-v0.12.0 Grdifinity bins due to rename of "MagnetRelief" to "MagnetRemoveChannel".
When using Gridfinity Workbench v0.12.0 to modify bins generated with an earlier (pre-v0.12.0) version (eg. change "Height Units"), the following error is generated by FreeCAD and the modified bin fails to be rebuilt:

```
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'MagnetRemoveChannel'
11:39:42  SimpleStorageBin005: 'FeaturePython' object has no attribute 'MagnetRemoveChannel'
```

This seems to have been caused by commit [055ac67](https://github.com/Stu142/FreeCAD-Gridfinity-Workbench/pull/116/changes/055ac6757bd0ec425c31c6ae43cab5a4b210631a) from PR #116.

A simple fix would be to consider reverting that commit to retain backward compatibility or that the break in compatibility be clearly documented for version 0.12.0 advising that gridfinity bins in pre-existing freecad files will have to be deleted and recreated.

### LINKED ISSUE #142: Error modifying pre-v0.12.0 Gridfinity bins due to failure to correctly update "UsableHeight" property.
Gridfinity wortkbench v0.12.0 fails to correctly modify Gridfinity bins created with v0.11.10 or earlier.

After loading a freecad file containing a gridfinity bin generated with Gridfinity Workbench v0.11.10 (or earlier), changes to the `HeightUnits` property will incorrectly regenerate the bin (see below). This seems it may be related to the fact that the `UsableHeight` property is not correctly updated after changing the `HeightUnits` property.

The issues seems related to commit [8093967](https://github.com/Stu142/FreeCAD-Gridfinity-Workbench/pull/129/changes/8093967ba561916d605ffc40e22871e36aae4fb9), where the calculation of `UsableHeight` is changed to use `obj.setProperty()`. The issue only seems to occur when opening pre-v0.11.10 gridfinity bins.

Note that selecting the `Recompute Object` options from the context menu also fails to trigger an update of the `UsableHeight` property.

### To reproduce this issue:

1. Select Gridfinity Workbench v0.11.10, or earlier (eg. `git checkout v0.11.10`)
2. Open Freecad and create a simple storage bin with Gridfinity Workbench v0.11.10 (or earlier)

Image

3. Save the bin in a test file and close freecad
4. Select Gridfinity Workbench v0.12.0  (eg. `git checkout v0.12.0`)
5. Open Freecad and open the test file: _The file opens and the bin renders correctly as above_. (In the property tab `UsableHeight=35mm`).

6. Change the `HeightUnits` property from `6` to `10`: _The outside bin changes height correctly, but the inside features remain as for `HeightUnits=6`_. (`UsableHeight` incorrectly remains at `35mm`).

Image

8. Change the `HeightUnits` property from `10` to `4`: _The base of the bin is cut off and the bin does not render correctly_. (`UsableHeight` incorrectly remains at `35mm`).

Image

### PR DESCRIPTION
**Pull request by glenn20**
Provide the `check_version.migrate_object_version()` function, which checks the version of the object against the current Gridfinity Workbench version, and if they are different, it will update the properties in the object to match the current version.

The function is called from `FoundationGridfinity.onDocumentRestored()` when loading a Gridfinity object generated by an older version of the workbench.

This provides a form of backward compatibilty for newer versions of the Gridfinity workbench.

A warning message is printed to the console when an object is updated from an older version.

The initial implementation only supports migrating objects from v0.11.9 and v0.11.10 to v0.12.0. In particular, this PR fixes Issue #141 and Issue #142 by renaming the "MagnetRelief"  property to "MagnetRemoveChannel" and setting the calculation of "UsableHeight" as an object Expression. It also converts the "xGridUnits" and "yGridUnits" properties from integer to float.

~NOTE: Gridfinity objects are **only** updated when their properties are modified. If an object is not modified, it will retain its old properties and version.~

This is an initial and straightforward implementation to address the Issues above. It necessarily duplicates code for creating and modifying the object properties. A more considered implementation would provide a mechanism for managing object schema migration. Nonetheless, this does address the immediate issues of broken backward compatibility.

Closes #141
Closes #142

### CODE REVIEW

File: freecad/gridfinity_workbench/features.py [hunk 1]
```diff
@@ -36,6 +87,14 @@ def __init__(self, obj: fc.DocumentObject) -> None:
         obj.Proxy = self
 
     def execute(self, fp: Part.Feature) -> None:
+        if str(getattr(fp, "version", "")) != __version__:
```
[the remark this answers is not in the document]
Comment (glenn20) [reply freecad/gridfinity_workbench/features.py]: I have implemented this request in commit [62d4082](https://github.com/Stu142/FreeCAD-Gridfinity-Workbench/pull/143/commits/62d40829f39a988104bcda35dd8e0f152ea27969).

Note that with this change gridfinity objects are force updated and recomputed on document load, rather than only if  and when you choose to modify the object properties in freecad. The prior behaviour may actually be considered to be more user-friendly.

**Comment by glenn20** [comment]
I have also refactored to move the property migration code into a new `check_version.py` module.

I have also squashed the commits for a cleaner PR.

**Comment by Stu142** [comment]
Great idea

**Comment by glenn20** [comment]
Thanks @Stu142 for a great project and thanks for the support and guidance @greg19.
